### ISSUE TITLE
`IOT instruction` when enabling and saving Stereoscopic 3D

### ISSUE THREAD

**Issue by kangalioo** [performous/performous#851]
### Performous & operating system versions

Performous: 1.2+
Operating system: Arch Linux 6.0.8 x86_64

### What is the problem?

In the Graphic settings, when setting Stereoscopic 3D from Disabled to Enabled and pressing Ctrl+S, the game crashes with `IOT instruction (core dumped)` printed to console

### Steps to reproduce

1. Open Performous
2. Navigate to Graphic settings
3. Toggle Stereoscopic 3D to "Enabled"
4. Press Ctrl+S

### Additional context

Terminal output after pressing Ctrl+S:
```
Wanting to change something, old value: 'English' new value: 'Auto'
locale/notice: Setting language to: 'Auto'
locale/notice: Current language is: 'Auto'
opengl/error: Shader [dancenote]: error: declarations for uniform `padding` are inside blocks `danceNote` and `stereoParams`
[1]    6442 IOT instruction (core dumped)  performous
```

GDB output:
```gdb
...
opengl/error: Shader [dancenote]: error: declarations for uniform `padding` are inside blocks `danceNote` and `stereoParams`

Thread 1 "performous" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
Downloading 0.00 MB source file /usr/src/debug/glibc/nptl/pthread_kill.c
44            return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;                                
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0)
    at pthread_kill.c:44
#1  0x00007ffff36a16b3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff3651958 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff363b53d in __GI_abort () at abort.c:79
#4  0x00007ffff3899833 in __gnu_cxx::__verbose_terminate_handler() ()
    at /usr/src/debug/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#5  0x00007ffff38a5cfc in __cxxabiv1::__terminate(void (*)()) (handler=<optimized out>)
    at /usr/src/debug/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#6  0x00007ffff38a5d69 in std::terminate() () at /usr/src/debug/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#7  0x00007ffff38a5fcd in __cxxabiv1::__cxa_throw(void*, std::type_info*, void (*)(void*))
    (obj=<optimized out>, tinfo=0x7ffff3a291e0 <typeinfo for std::runtime_error>, dest=0x7ffff38bd470 <std::runtime_error::~runtime_error()>) at /usr/src/debug/gcc/libstdc++-v3/libsupc++/eh_throw.cc:98
#8  0x0000555555576665 in  ()
#9  0x000055555566e942 in  ()
#10 0x00005555555c3afe in  ()
#11 0x0000555555614d41 in  ()
#12 0x00005555555f98c4 in  ()
#13 0x00005555555fd3b0 in  ()
#14 0x000055555558d1ec in  ()
#15 0x00007ffff363c290 in __libc_start_call_main
     (main=main@entry=0x55555558b510, argc=argc@entry=1, argv=argv@entry=0x7fffffffd6d8) at ../sysdeps/nptl/libc_start_call_main.h:58
#16 0x00007ffff363c34a in __libc_start_main_impl
     (main=0x55555558b510, argc=1, argv=0x7fffffffd6d8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffd6c8) at ../csu/libc-start.c:381
#17 0x00005555555933d5 in  ()
```

### Log(s) & preferences file(s)

[infolog.txt](https://github.com/performous/performous/files/10327536/infolog.txt)
[config.xml](https://github.com/performous/performous/files/10327538/config.xml.txt)

**Comment by Baklap4** [comment]
@OznOg @Lord-Kamina i thought you touched this part fairly recently, is this the same bug?
Linked PR for this was: https://github.com/performous/performous/pull/755

**Comment by Lord-Kamina** [comment]
Yes,we fixed this a while ago.

**Comment by Baklap4** [comment]
Closing this as it's already been fixed in mentioned PR.
Meanwhile @kangalioo please use the latest build (which can be downloaded from our readme file)
